[package]
name = "qbf"
version = "0.1.0"
authors = ["Leander Tentrup <tentrup@react.uni-saarland.de>"]

[dependencies]
cryptominisat = "5.0.1"
log = "0.4"
simplelog = "^0.5.0"
siphasher = "~0.1"  # for deterministic has functions
bit-vec = "0.4.4"

[features]
statistics = [] # enable statistics

[profile.release]
opt-level = 3
panic = "abort"
lto = true
codegen-units = 1
incremental = false
