[package]
name = "caqe"
version = "4.0.0-dev"
authors = ["Leander Tentrup <tentrup@react.uni-saarland.de>"]

[dependencies]
cryptominisat = "5.0.1"
log = { version = "0.4", features = ["release_max_level_warn"] }
simplelog = "^0.5.0"
bit-vec = "0.5.0"
tempfile = "3.0.1"    # for first running preprocessor and piping result to temporary
clap = "2.31.2"       # parsing command line arguments
rustc-hash = "1.0.1"  # fast, non-randomized HashMap/HashSet

[patch.crates-io]
cryptominisat = { git = "https://github.com/ltentrup/cryptominisat-rs.git" }

[features]
statistics = [] # enable statistics

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
incremental = false

