[package]
name = "qbf"
version = "0.1.0"
authors = ["Leander Tentrup <tentrup@react.uni-saarland.de>"]

[dependencies]
cryptominisat = "5.0.1"
log = "0.4"
simplelog = "^0.5.0"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
